// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANsNwZvCrFNV1jZkOkXTrkHdfOQlUhz80',
    appId: '1:787848155175:web:01049b819ce5f7987ebe02',
    messagingSenderId: '787848155175',
    projectId: 'clubhouse-c0a58',
    authDomain: 'clubhouse-c0a58.firebaseapp.com',
    storageBucket: 'clubhouse-c0a58.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjCyJU2IKjDkE1w-Tjq0Po_ROXGHnO69E',
    appId: '1:787848155175:android:7c6dd1109723b29d7ebe02',
    messagingSenderId: '787848155175',
    projectId: 'clubhouse-c0a58',
    storageBucket: 'clubhouse-c0a58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhoGXsoCxBppdNjJl2hwl_VrbcDQJDcnM',
    appId: '1:787848155175:ios:10bf5727df811f927ebe02',
    messagingSenderId: '787848155175',
    projectId: 'clubhouse-c0a58',
    storageBucket: 'clubhouse-c0a58.appspot.com',
    iosClientId: '787848155175-j4dv7ur4eep9fpb1klkba0d2ngad4jgt.apps.googleusercontent.com',
    iosBundleId: 'com.example.clubHouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhoGXsoCxBppdNjJl2hwl_VrbcDQJDcnM',
    appId: '1:787848155175:ios:10bf5727df811f927ebe02',
    messagingSenderId: '787848155175',
    projectId: 'clubhouse-c0a58',
    storageBucket: 'clubhouse-c0a58.appspot.com',
    iosClientId: '787848155175-j4dv7ur4eep9fpb1klkba0d2ngad4jgt.apps.googleusercontent.com',
    iosBundleId: 'com.example.clubHouse',
  );
}
